<a href="https://colab.research.google.com/github/Venumurala91/Numpy/blob/main/matplotlib_%26_seaborn_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df_train=pd.read_csv('/content/black_Friday_train.csv.csv')
df_train.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1000004,P00128942,M,46-50,7.0,B,2,1.0,1.0,11.0,NaN
1,1000009,P00113442,M,26-35,17.0,C,0,0.0,3.0,5.0,NaN
2,1000010,P00288442,F,36-45,1.0,B,4+,1.0,5.0,14.0,NaN
3,1000010,P00145342,F,36-45,1.0,B,4+,1.0,4.0,9.0,NaN
4,1000011,P00053842,F,26-35,1.0,C,1,0.0,4.0,5.0,12.0

In [17]:
df_test=pd.read_csv('/content/black_Friday_train.csv.csv')
df_test.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [19]:
df=df_train

In [20]:
df.shape

(76550, 11)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76550 entries, 0 to 76549
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     76550 non-null  int64
 1   Product_ID                  76550 non-null  object
 2   Gender                      76550 non-null  object
 3   Age                         76550 non-null  object
 4   Occupation                  76549 non-null  float64
 5   City_Category               76549 non-null  object
 6   Stay_In_Current_City_Years  76549 non-null  object
 7   Marital_Status              76549 non-null  float64
 8   Product_Category_1          76549 non-null  float64
 9   Product_Category_2          52957 non-null  float64
 10  Product_Category_3          23331 non-null  float64
dtypes: float64(5), int64(1), object(5)
memory usage: 6.4+ MB

In [22]:
df.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
count,7.655000e+04,76549.000000,76549.000000,76549.000000,52957.000000,23331.000000
mean,1.002988e+06,8.103646,0.411005,5.261218,9.842740,12.681540
std,1.717848e+03,6.507160,0.492019,3.737411,5.098576,4.115936
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000
25%,1.001496e+06,2.000000,0.000000,1.000000,5.000000,9.000000
50%,1.003013e+06,7.000000,0.000000,5.000000,9.000000,14.000000
75%,1.004420e+06,14.000000,1.000000,8.000000,15.000000,16.000000
max,1.006040e+06,20.000000,1.000000,18.000000,18.000000,18.000000

In [ ]:
df.drop(['User_ID'],axis=1,inplace=True)

In [26]:
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,P00128942,M,46-50,7.0,B,2,1.0,1.0,11.0,NaN
1,P00113442,M,26-35,17.0,C,0,0.0,3.0,5.0,NaN
2,P00288442,F,36-45,1.0,B,4+,1.0,5.0,14.0,NaN
3,P00145342,F,36-45,1.0,B,4+,1.0,4.0,9.0,NaN
4,P00053842,F,26-35,1.0,C,1,0.0,4.0,5.0,12.0

In [29]:
df['Gender']=pd.get_dummies(df['Gender'],drop_first=1)

df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,P00128942,True,46-50,7.0,B,2,1.0,1.0,11.0,NaN
1,P00113442,True,26-35,17.0,C,0,0.0,3.0,5.0,NaN
2,P00288442,False,36-45,1.0,B,4+,1.0,5.0,14.0,NaN
3,P00145342,False,36-45,1.0,B,4+,1.0,4.0,9.0,NaN
4,P00053842,False,26-35,1.0,C,1,0.0,4.0,5.0,12.0

In [33]:
##HAndling categorical feature Gender
df['Gender']=df['Gender'].map({'F':0,'M':1})
df.head()

df['Gender']=df['Gender']

In [34]:
##fixing categorical City_categort
df_city=pd.get_dummies(df['City_Category'],drop_first=True)

In [35]:
df_city.head()

       B      C
0   True  False
1  False   True
2   True  False
3   True  False
4  False   True

In [9]:
df=pd.concat([df,df_city],axis=1)
df.head()

NameError: name 'df' is not defined

In [38]:
##drop City Category Feature
df.drop('City_Category',axis=1,inplace=True)

KeyError: "['City_Category'] not found in axis"

In [39]:
df.head()

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,B,C
0,P00128942,NaN,5.0,7.0,2,1.0,1.0,11.0,NaN,True,False
1,P00113442,NaN,3.0,17.0,0,0.0,3.0,5.0,NaN,False,True
2,P00288442,NaN,4.0,1.0,4+,1.0,5.0,14.0,NaN,True,False
3,P00145342,NaN,4.0,1.0,4+,1.0,4.0,9.0,NaN,True,False
4,P00053842,NaN,3.0,1.0,1,0.0,4.0,5.0,12.0,False,True

In [40]:
df.isnull().sum()

Product_ID                        0
Gender                        76550
Age                               1
Occupation                        1
Stay_In_Current_City_Years        1
Marital_Status                    1
Product_Category_1                1
Product_Category_2            23593
Product_Category_3            53219
B                                 0
C                                 0
dtype: int64

In [41]:
## Focus on replacing missing values
df['Product_Category_2'].unique()

array([11.,  5., 14.,  9.,  3.,  4., 13.,  2., nan,  8., 15., 17., 12.,
       16.,  6., 10., 18.,  7.])

In [5]:
df['Product_Category_2'].value_counts()

NameError: name 'df' is not defined

In [43]:
df['Product_Category_2'].mode()[0]

np.float64(8.0)

In [45]:
df['Product_Category_2']=df['Product_Category_2'].fillna(df['Product_Category_2'].mode()[0])

In [46]:
df['Product_Category_2'].isnull().sum()

np.int64(0)

In [48]:
df['Product_Category_3'].unique()

array([nan, 12., 15.,  9., 16., 14.,  4.,  3.,  5.,  8., 17., 13., 11.,
       10.,  6., 18.])

In [49]:
df['Product_Category_3'].value_counts()

Product_Category_3
16.0    4578
15.0    3939
14.0    2627
5.0     2342
17.0    2314
8.0     1686
9.0     1628
12.0    1291
13.0     773
6.0      672
18.0     637
4.0      259
10.0     256
11.0     244
3.0       85
Name: count, dtype: int64

In [1]:
df['Product_Category_3']=df['Product_Category_3'].fillna(df['Product_Category_3'].mode()[0])

NameError: name 'df' is not defined

In [ ]:
df.head()

In [11]:
df['Product_Category_3'].value_counts()

NameError: name 'df' is not defined